Natallia dev
valentinavolgina2/sunny-hikes pull request #97
Opened 2022-03-25 04:08 UTC by NatalliaKazheunikava

2022-03-25 15:20 UTC, valentinavolgina2 requested changes
Could you please address my comment doe loadMore.js file?

2022-03-25 15:20 UTC, valentinavolgina2 commented on public/script/review/loadMore.js
> +        if(!currentUser.blocked) {
it's better to do it this way:
`if(currentUser && !currentUser.blocked && (isReviewer || reviewIsMine))`

2022-03-26 20:03 UTC, NatalliaKazheunikava commented on public/script/review/loadMore.js
> +        if(!currentUser.blocked) {
Oh yes, absolutely.

2022-03-26 22:20 UTC, valentinavolgina2 approved these changes

2022-03-26 22:21 UTC, merged